<a href="https://colab.research.google.com/github/bhargavigulla57/python_code/blob/main/Adding_and_Subtracting_Matrices.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
A = np.array([[1, 2], [3, 4]])
B = np.array([[4, 5], [6, 7]])

print("Matrix A:\n", A)
print("Matrix B:\n", B)

# Adding matrices
C = np.add(A, B)
print("Result:\n", C)

Matrix A:
 [[1 2]
 [3 4]]
Matrix B:
 [[4 5]
 [6 7]]
Result:
 [[ 5  7]
 [ 9 11]]
