<a href="https://colab.research.google.com/github/bhargavigulla57/python_code/blob/main/Matrix_of_two_numbers.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:

import numpy as np

a = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
b = np.array([[9, 8, 7], [6, 5, 4], [3, 2, 1]])
res = a + b
print(res)

[[10 10 10]
 [10 10 10]
 [10 10 10]]
