<a href="https://colab.research.google.com/github/bhargavigulla57/python_code/blob/main/Multiply_Two_Matrices.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

A = [[12, 7, 3],
     [4, 5, 6],
     [7, 8, 9]]

B = [[5, 8, 1, 2],
     [6, 7, 3, 0],
     [4, 5, 9, 1]]

r = np.dot(A, B)
for row in r:
    print(row)

[114 160  60  27]
[74 97 73 14]
[119 157 112  23]
