<a href="https://colab.research.google.com/github/bhargavigulla57/python_code/blob/main/Python_Programs_to_Transpose_a_matrix_using_NumPy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
matrix = np.array([[1, 2, 3], [4, 5, 6]])
print(matrix)
print("\n")
print(matrix.T)


[[1 2 3]
 [4 5 6]]


[[1 4]
 [2 5]
 [3 6]]
